### ISSUE TITLE
Progress bar never stops

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/search_api#15]
![Screenshot from 2020-12-11 12-52-33](https://user-images.githubusercontent.com/1071483/101937353-c11ab280-3baf-11eb-90ba-b7b18973289e.png)

Looks like everything is finished indexing but the progress bar doesn't stop.

**Comment by earlyburg** [comment]
![search_api_scrnsht_drpl](https://user-images.githubusercontent.com/36900097/102802107-2fb3f900-4384-11eb-9aa5-1157f323816b.png)

In  D7, the progress bar  displays as filled or full. I'm downgrading this issue from 'bug' to 'good first issue', because it's technically not broken, but needs upgrading.

**Comment by earlyburg** [comment]
@herbdool Hi,
I authored a fix for this - It will go out with the next release. You can view it here:
https://github.com/backdrop-contrib/search_api/commit/db27b5b7c9659e0c376e792c1bd1192111cb0790
Turned out to be an easy CSS tweak. Thanks for pointing it out, I appreciate it!
Closing this issue - Fixed / Upgraded
