### ISSUE TITLE
Views integration not working

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/search_api#3]
> The one main thing that wasn't working for me was when creating a View. I attempted some debugging but stopped because of other priorities.

(Pasted from [a comment in another thread](https://github.com/backdrop-contrib/search_api/issues/1#issuecomment-622431363))

**Comment by earlyburg** [comment]
@laryn This issue is most likely the result of reduced views support in the core entity module.
Function entity_views_field_definition() is referenced twice in search_api_views.views.inc, on lines 43 and 175, but this function is no longer a part of entity nor a part of entity plus. 
The function was originally located in the drupal 7 entity module in entity.views.inc on line 175

This functionality may be a good addition to the [entity plus module](https://github.com/backdrop-contrib/entity_plus). If it's ok I will work something up and submit a pull request for it.

**Comment by earlyburg** [comment]
Hello,
We have upgraded entity_plus with the required functionality needed to fix this issue. I have created a pull request:
https://github.com/backdrop-contrib/search_api/pull/11

**Comment by laryn** [comment]
Maybe good to specify a minimum version of entity plus in the dependency.

**Comment by earlyburg** [comment]
@laryn 
I have added a minimum version requirement and updated READMEs as well. Thanks for pointing that out.
Also. may I please be added to the list of maintainers? 
https://github.com/backdrop-contrib/search_api/issues/10
